openapi: 3.0.0
info:
  description: This is API specification for MySite project.
  title: Mysite API specification
  version: '1.0'
servers:
  - url: /
security:
  - {}
tags:
  - name: health
    description: Health Feature
paths:
  /health:
    get:
      operationId: health
      summary: Get health
      description: Get health
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /register:
    post:
      operationId: register
      summary: Register user
      description: Register user
      tags:
        - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: created
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /login:
    post:
      operationId: login
      summary: login
      description: login
      tags:
        - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 'return cookies with keys -''accessToken'', ''refreshToken'''
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /refresh:
    post:
      operationId: refresh
      summary: refresh token api
      description: refresh token api
      tags:
        - refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: return cookies with keys -'accessToken'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HealthResponse:
      type: object
      description: Error Response Object
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      description: Error Response Object
      properties:
        appCode:
          type: integer
        errorText:
          type: string
        statusText:
          type: string
    RegisterRequest:
      type: object
      description: register request body
      properties:
        userName:
          type: string
          description: email
        password:
          type: string
          description: password
        name:
          type: string
          description: name of user
        phone:
          type: string
          description: phone number of user
        email:
          type: string
          description: email of user
        gender:
          type: string
          description: 'enum of [male, female, other]'
      required:
        - userName
        - password
    LoginRequest:
      type: object
      description: login request body
      properties:
        userName:
          type: string
          description: email
        password:
          type: string
          description: password
      required:
        - userName
        - password
    RefreshRequest:
      type: object
      description: refresh token request body
      properties:
        refreshToken:
          type: string
          description: refresh token
      required:
        - refreshToken
