openapi: 3.0.0
info:
  description: This is API specification for MySite project.
  title: Mysite API specification
  version: "1.0"
servers:
  - url: /
security:
  - {}
tags:
  - name: health
    description: Health Feature

paths:
  /health:
    get:
      $ref: ./features/health/get.yml
  /register:
    post:
      $ref: ./features/register/post.yml
  /login:
    post:
      $ref: ./features/login/post.yml
  /refresh:
    post:
      $ref: ./features/refresh/post.yml
  
components:
  schemas:
    HealthResponse:
      $ref: ./features/health/HealthResponse.yml
    ErrorResponse:
      $ref: ./features/common/ErrorResponse.yml
    RegisterRequest:
      $ref: ./features/register/RegisterRequest.yml
    LoginRequest:
      $ref: ./features/login/LoginRequest.yml
    RefreshRequest:
      $ref: ./features/refresh/RefreshRequest.yml
