// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package model

// HealthResponse Error Response Object
type HealthResponse struct {
	Message *string `json:"message,omitempty"`
}
