// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package model

// ErrorResponse Error Response Object
type ErrorResponse struct {
	AppCode    *int    `json:"appCode,omitempty"`
	ErrorText  *string `json:"errorText,omitempty"`
	StatusText *string `json:"statusText,omitempty"`
}

// HealthResponse Error Response Object
type HealthResponse struct {
	Message *string `json:"message,omitempty"`
}

// LoginRequest login request body
type LoginRequest struct {
	// Password password
	Password string `json:"password"`

	// UserName email
	UserName string `json:"userName"`
}

// RefreshRequest refresh token request body
type RefreshRequest struct {
	// RefreshToken refresh token
	RefreshToken string `json:"refreshToken"`
}

// RegisterRequest register request body
type RegisterRequest struct {
	// Email email of user
	Email *string `json:"email,omitempty"`

	// Gender enum of [male, female, other]
	Gender *string `json:"gender,omitempty"`

	// Name name of user
	Name *string `json:"name,omitempty"`

	// Password password
	Password string `json:"password"`

	// Phone phone number of user
	Phone *string `json:"phone,omitempty"`

	// UserName email
	UserName string `json:"userName"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest
