// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package model

// ErrorResponse Error Response Object
type ErrorResponse struct {
	AppCode    *int    `json:"appCode,omitempty"`
	ErrorText  *string `json:"errorText,omitempty"`
	StatusText *string `json:"statusText,omitempty"`
}

// HealthResponse Error Response Object
type HealthResponse struct {
	Message *string `json:"message,omitempty"`
}

// RegisterRequest register request body
type RegisterRequest struct {
	// Password password
	Password string `json:"password"`

	// UserName email
	UserName string `json:"userName"`
}

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest
