// Code generated by SQLBoiler 4.16.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

var TableNames = struct {
	UserAccount string
	UserInfo    string
}{
	UserAccount: "user_account",
	UserInfo:    "user_info",
}
